### ISSUE TITLE
convert_args! doesn't work with vec! and square brackets

### ISSUE THREAD

**Issue by tecywiz121** [bluss/maplit#21]
This is a fairly minor issue, but is annoying since we use rustfmt.

For better or worse, rustfmt converts `vec!(...)` to `vec![...]`. If you use `convert_args!(vec!(...))` it compiles just fine, but `convert_args!(vec![...])` does not.

**Comment by bluss** [comment]
Combining macros like this was deemed idiomatic (see nom, it prefers ()'s), so it seems like an issue with rustfmt.

**Comment by bluss** [comment]
Since vec is not defined in this crate, I'll decline this issue with the above comment for now; convert_args is designed for the macros in this crate, even though I of course understand that it can be used more widely.

**Comment by tecywiz121** [comment]
Would you accept a PR expanding the macro with another pattern that matches other bracket types?
