### ISSUE TITLE
cannot find macro `lazy_static` in this scope

### ISSUE THREAD

**Issue by hoijui** [bluss/maplit#36]
```
cargo clippy --release -- --deny clippy::pedantic --verbose
    Checking maplit v1.0.2
error: cannot find macro `lazy_static` in this scope
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/maplit-1.0.2/src/lib.rs:46:1
   |
46 | lazy_static!{
   | ^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `maplit`
```

**Comment by hoijui** [comment]
The same error appears when i compile my project with `cargo build`, but not when compiling with `cargo build --release`.

**Comment by bluss** [comment]
There is no lazy_static usage in this crate, so it's hard to see how it's relevant or connected to maplit. More complete code would be needed to reproduce.

**Comment by hoijui** [comment]
... ouhh... I am sorry!
I had the same problem again. I just deleted `/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/`,
after which the problem went away. ;-)
Apparently I must have edited it, while browsing around my dependencies in VSCodium. I am not used to be able ot actually edit dependencies code when browsing it in an IDE.
... sorry!!
