### ISSUE TITLE
Question: usefulness?

### ISSUE THREAD

**Issue by sanmai-NL** [bluss/maplit#5]
The apparent purpose of this crate interests me, since I miss C++'s initializer list in Rust. But when checking it out, I was left wondering whether it is worthwhile to adopt it. Could you write a few words in the project `README` about how these macros are useful? Is there a performance difference vs. using only the standard library? Is the advantage in the ergonomics in the sense of being more readable (straightforward)? And/or being less verbose? Is it not having bind the variable mutably, and then again immutably to remove the mutability?

I deliberately did not yet check the source code to find out, since many developers will not want to have to do that for such a ‘minor’ aspect of their code. So I think adding a motivation would be useful since there is outside interest in this crate, me being just an example.

**Comment by bluss** [comment]
I think the use case is convenience. The crate doesn't have an opinion about if you should use it or not, it's up to you.

We don't keep bugs open for suggesting to improve docs, instead PRs are simply welcome to do so (although a meta-discussion about the crate seems to be a stretch).
